### ISSUE TITLE
Funkcionalita pro Nový inzerát

### ISSUE THREAD

**Issue by zabaanto** [jandoubek/fjfi-pvs-inzeraty#10]
- nekam umistit mostnost ,,Novy inzerat"
- provazat vyplneni inzeratu s databazi
- Roman v rámci #8 úkaže jak by se měl dělat ajax a komunikace s DB (ajax v Nette a tak)

**Comment by zabaanto** [comment]
@bohuslavpetr Pripravi(l) editaci inzeratu, vyuzit podobnou strukturu _inzerat.latte_ i pro novy inzerat. Zatim staci zalozeni inzeratu jen s jednoduchyma prvkama: nadpis, kategorie, popis, cena.

Galerii zatim nedelat, je slozitejsi, udela se na ni zvlast issue.

**Comment by zabaanto** [comment]
Spolupracovat s @bohuslavpetr

**Comment by prcharom** [comment]
Bylo to jedine, ale s prepisovanim, abych to hodil do cajku, jsem se delal 4 hodiny. Ten template u toho inzeratu je fakticky obrovska zrudnost. Doporucuji formularove prvky vypisovat nettacky pomoci makra {input nazevInputu}, protoze pak lze z pressenteru k temto imputum pristupovat a lze do nich nalejvat hodnoty nactene z db apod. Jinak už je to vyresene a funguje jak pridavani inzeratu, tak i editace.

**Comment by prcharom** [comment]
No asi bych uz vazne mel jit spat :-D :D ono uz je pul paty :-D
