### ISSUE TITLE
Bug s modal okny

### ISSUE THREAD

**Issue by zabaanto** [jandoubek/fjfi-pvs-inzeraty#15]
Napriklad po chybnem prihlaseni by se melo info o spatnem vyplneni hesla ci jmena napsat nekde do popUpu. Misto toho dojde k presmerovani no novou stranku, kde se chyba vypise. To same se deje i pri registraci.

**Nutno poresit co nejdriv!!!**

Bud to vyresit v ramci nette nebo vyuzit surové jQuery a rucne vypisovat chybove hlasky primo do pupUpu.

**Comment by prcharom** [comment]
FIXED ^^

**Comment by prcharom** [comment]
V commitu jsem dal špatné id, commit jsem přiřadil k #8 a nevím, kde to opravit, každopádně problém je vyřešen.

**Comment by zabaanto** [comment]
Fixed by @prcharom  with commit: fadaff5ca38298911fe1107b364207a6249c6946

**Comment by zabaanto** [comment]
Stejnou vec opravit pro registraci!

**Comment by prcharom** [comment]
Fixed ^-^
