### ISSUE TITLE
Uzavreni inzeratu

### ISSUE THREAD

**Issue by zabaanto** [jandoubek/fjfi-pvs-inzeraty#19]
- implementovat moznost uzavreni inzeratu (pouze pro autora inzeratu)

**Comment by prcharom** [comment]
Klidne bych si to vzal pod kridla, kdyz mi to priradis. Nechci na tom makat dopredu, kdyby si to nahodou už nekomu dal a jen ho tu nepriradil. :-)

**Comment by prcharom** [comment]
Hotovo.. Funkčnost tam je, mozna bude treba hybat s designem, hodil jsem ho hodne obyc.

**Comment by zabaanto** [comment]
Proč není deaktivace inzeratu jednoduše uvnitr editace inzeratu?

_Moje inzeraty_ bych si spis predstavoval jednoduse ve stylu kategorie _Nejaktualnejsi inzeraty_. V teto podobe je to sice pekny, ale vypis _Mych inzeratu_ je v teto podobe zameren pouze na jejich deaktivaci.

Do seznamu mych inzeratu jdu s cilem nejaky upravit (deaktivaci mohu provest po otevreni inzeratu). Pochybuju, ze jich budu chtit deaktivovat vice najednou.

Aktualne navic resim, ze bootstrap moc nepodporuje zanorenost modalnich oken, takze po kliku na inzerat v seznamu a o otevrit ho v dalsim modalnim okne moc nepujde.

Navic kategorii _Moje inzeraty_ ma na starost @pribyto4 v ramci #17 .

**Comment by prcharom** [comment]
Jasnacka, tak ja potreboval nejak resit aktivaci a deaktivaci inzeratu. Na druhou stranu takhle ma uzivatel prehled, ktery inzeraty ma aktivni a ktere ne. Navic neni problem pridat tam odkaz na editaci jednotlivych inzeratu, ale je mi to jedno, klidne to muzu predelat. No problemo.

**Comment by zabaanto** [comment]
Ten prehled zachovame, jen premistime jinam. Pripadne do nej pridame i odkazy. Zatim to takhle nech.
