### ISSUE TITLE
Skrolovani v popUpu

### ISSUE THREAD

**Issue by zabaanto** [jandoubek/fjfi-pvs-inzeraty#20]
**Aby nedochazelo ke skrolovani v popUpu**
- kam jinam dat inzerat nez do PopUpu, aby nedochazelo ke skrolovani
- jak jinak strukturovat inzerat, aby nedochazelo ke skrolovani

**Comment by prcharom** [comment]
V čem vadí scrolování? Jinak reseni me napada bud rozsekat na jednotlive casti, info, komentare a udelat preklikavani. Pokud to neni  reseni, ktere by se nam libilo, tak jedina moznost je neumistovat detail do popupu ale presmerovat ho na novou stranku.

**Comment by zabaanto** [comment]
Na jine reseni neni zatim cas, tak bych ponechal v PopUpu.
