### ISSUE TITLE
Editace galerie v inzeratu

### ISSUE THREAD

**Issue by zabaanto** [jandoubek/fjfi-pvs-inzeraty#21]
Pri editaci inzeratu implementovat editaci galerie.

**Comment by prcharom** [comment]
Jo takhle tys na me hodil celou galerii i pridavani novych fotek, vse komplet?

**Comment by zabaanto** [comment]
ckj, Kdyz jsi nakonec pracoval na editaci inzeratu, tak to samozrejme nedostanes ;) ..navic jsem si tu zduplikoval ukoly ke galerii, nejak jsem to popletl.

**Comment by prcharom** [comment]
No já tenhle tyden delal, ze jsem odstranil bug u toho modalu u registrace, pak jsem doladil editaci inzeratu a vcera jsem docvaknul moznost predcasneho stazeni a znovu publikovani inzeratu. Asi zitra na PVS nebudu, tak to mas tady cerne na bilem co jsem delal. Do dalsiho tydne mi zase cokoliv pridel a ja to udelam dle moznosti.

**Comment by pribyto4** [comment]
uložení inzerátů do databáze @bohuslavpetr 
 a37bd9db6b0c5e655d4a0b13ba0f4e6ce0518a49

**Comment by zabaanto** [comment]
Spolupracovat s @prcharom  a se mnou.
