### ISSUE TITLE
Zarovnani miniatur na hlavni strance

### ISSUE THREAD

**Issue by zabaanto** [jandoubek/fjfi-pvs-inzeraty#22]
Ten inline-block zkus vratit zpatky a zkus spis hledat problem, proc se v safari vytvarej ty bily mista tak, ze miniatury pak ruzne skacou.

o reseni mozna pisou tu:

http://absolide.tumblr.com/post/36597829434/safari-inline-block-white-spaces-bug-fix

**Comment by pribyto4** [comment]
poslední řádka inzerátů (když řádek není plný) je zarovnána na střed, jinak mi to nešlo
