### ISSUE TITLE
Galerie - novy inzerat, vypis inzeratu, editace inzeratu

### ISSUE THREAD

**Issue by zabaanto** [jandoubek/fjfi-pvs-inzeraty#24]
- pri tvorbe noveho a editaci existujiciho inzeratu pouzivat stejny mechanismus, at je to pro uzivatele jednolity

**Comment by prcharom** [comment]
Novy inzerat a editace inzeratu je resena v issue #10 ne? Uz jsme to s Hubitomem dodělali. Respektive on položil kostru a já to jen doladil.

**Comment by zabaanto** [comment]
Ale ja tu mam namysli pouze galerii

**Comment by pribyto4** [comment]
duplicitní issue, řešeno v #21
